  # Site settings
name: LessIs More 
email: liuliaocheng@sina.cn
author: ZealerDrm
url: http://liuliaocheng.github.io 
resume_site: http://liushuqian.me
github: https://github.com/liuliaocheng/
baseurl: ''
gems: [jekyll-paginate]

description: 生命中最难的阶段不是没人懂你，而是你不懂你自己
meta_description: 个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: 不信邪的人
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: liuliaocheng
#highlighter: rouge
#highlighter: pygments

# Build settings
markdown: kramdown

FB:
  comments :
    provider : wyy
    #duoshuo:
    #    short_name : ！！！
    #disqus :
    #    short_name : ！！！ss
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
    
